drop table APPLY_PLAY_CLASS;
drop table PARENT;
drop table STORE_PLAY_CLASS;
drop table STORE;
drop table PLAY_CLASS;

CREATE TABLE PARENT
(
    ID           BIGINT NOT NULL,
    NAME         VARCHAR(255),
    EMAIL        VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID)
);

CREATE TABLE PLAY_CLASS
(
    ID              BIGINT NOT NULL,
    NAME            VARCHAR(255),
    MAX_STUDENT_CNT INTEGER,
    CREATED_DATE    TIMESTAMP,
    UPDATED_DATE    TIMESTAMP,
    CONSTRAINT CONSTRAINT_C PRIMARY KEY (ID)
);

CREATE TABLE STORE
(
    ID           BIGINT NOT NULL,
    NAME         VARCHAR(255),
    ADDRESS      VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID)
);

CREATE TABLE STORE_PLAY_CLASS
(
    ID            BIGINT NOT NULL,
    STORE_ID      BIGINT,
    PLAY_CLASS_ID BIGINT,
    CREATED_DATE  TIMESTAMP,
    UPDATED_DATE  TIMESTAMP,
    CONSTRAINT CONSTRAINT_D PRIMARY KEY (ID),
    CONSTRAINT FK_PLAY_CLASS FOREIGN KEY (PLAY_CLASS_ID) REFERENCES PLAY_CLASS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_STORE FOREIGN KEY (STORE_ID) REFERENCES STORE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE APPLY_PLAY_CLASS
(
    ID                 BIGINT NOT NULL AUTO_INCREMENT,
    PARENT_ID          BIGINT,
    STORE_PLAYCLASS_ID BIGINT,
    APPLY_CHILD_CNT    INTEGER,
    STATUS             CHARACTER VARYING(255),
    APPLY_DATE         TIMESTAMP,
    CREATED_DATE       TIMESTAMP,
    UPDATED_DATE       TIMESTAMP,
    CONSTRAINT CONSTRAINT_7 CHECK (("STATUS" IN ('APPLY', 'CANCEL'))),
    CONSTRAINT CONSTRAINT_71 PRIMARY KEY (ID),
    CONSTRAINT FK_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PARENT (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_STORE_PLAY_CLASS FOREIGN KEY (STORE_PLAYCLASS_ID) REFERENCES STORE_PLAY_CLASS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
